version: "3"

services:
  frontend:
    container_name: app_frontend
    build:
      dockerfile: Dockerfile
      context: ./frontend
    # 볼륨을 설정합니다.
    volumes:
      - /app/node_modules
      - ./frontend:/app
    # 리액트 애플리케이션에서 발생하는 버그 해결
    stdin_open: true
  backend:
    container_name: app_backend
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8080:8080"
    env_file: ./.env
#    environment:
#      SPRING_DATASOURCE_URL:
#      SPRING_DATASOURCE_USERNAME:
#      SPRING_DATASOURCE_PASSWORD:
#      SPRING_PROFILES_ACTIVE:
  nginx:
    container_name: app_nginx
    restart: always
    volumes:
      - ./certbot/data/certbot/conf:/etc/letsencrypt
      - ./certbot/data/certbot/www:/var/www/certbot
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/data/certbot/conf:/etc/letsencrypt
      - ./certbot/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"