spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL;
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console

current.profile: local

---
spring:
  config:
    activate:
      on-profile: sandbox
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

current.profile: sandbox

---
spring:
  config:
    activate:
      on-profile: production

current.profile: production